### ISSUE TITLE
Use package:ffigen to generate bindings

### ISSUE THREAD

**Issue by dcharkes** [google/webcrypto.dart#15]
I've taken a stable at generating the bindings with `package:ffigen`.

With https://github.com/dart-lang/ffigen/issues/173 addressed, I can make it work on the host machine.

<details>
<summary>
However, without addressing https://github.com/dart-lang/sdk/issues/36140 and https://github.com/dart-lang/ffigen/issues/7, some of the integer sizes are not generated the right size for cross platform bindings.
</summary>

```c
// EVP_MD_size returns the digest size of |md|, in bytes.
OPENSSL_EXPORT size_t EVP_MD_size(const EVP_MD *md);
```

Handwritten bindings:

```dart
/// EVP_MD_size returns the digest size of md, in bytes.
///
/// ```c
/// size_t EVP_MD_size(const EVP_MD *md);
/// ```
final EVP_MD_size = resolve(Sym.EVP_MD_size)
    .lookupFunc<IntPtr Function(Pointer<EVP_MD>)>()
    .asFunction<int Function(Pointer<EVP_MD>)>();
```

Generated bindings (notice `Uint64` instead of `IntPtr`):

```dart
  /// // EVP_MD_size returns the digest size of |md|, in bytes.
  int EVP_MD_size(
    ffi.Pointer<env_md_st> md,
  ) {
    return (_EVP_MD_size ??=
        _lookup<ffi.NativeFunction<_c_EVP_MD_size>>('EVP_MD_size')
            .asFunction<_dart_EVP_MD_size>())(
      md,
    );
  }

  _dart_EVP_MD_size? _EVP_MD_size;

typedef _c_EVP_MD_size = ffi.Uint64 Function(
  ffi.Pointer<env_md_st> md,
);

typedef _dart_EVP_MD_size = int Function(
  ffi.Pointer<env_md_st> md,
);
```

</details>

Edit: We have a workaround

```yaml
typedef-map:
  'size_t': 'IntPtr`
```

Experiment: https://github.com/google/webcrypto.dart/tree/use-ffigen (ignore all the code duplication and pointer casts, I just wanted to migrate a single file).

**Comment by dcharkes** [comment]
@mannprerak2 please take a look at https://github.com/google/webcrypto.dart/tree/use-ffigen-2.

* The structs `CBS` and `CBB` do not get any fields when I do not specify `structs: - 'nothing'` (see diff last commit). What behavior is causing this?
* Can we filter constants? There are over 5000 in BoringSSL.

**Comment by mannprerak2** [comment]
> The structs CBS and CBB do not get any fields when I do not sp...

I can't seem to see any difference in the fields generated in the diff, could you copy the results from before and after?

> Can we filter constants? There are over 5000 in BoringSSL.

Yes depending on the type, you can include/exclude `unnamed-enums` or `macros`.

**Comment by dcharkes** [comment]
> can't seem to see any difference in the fields generated in the diff, could you copy the results from before and after?

My bad, I committed the one that I fixed up manually. It generated them as `Opaque`.

> Yes depending on the type, you can include/exclude `unnamed-enums` or `macros`.

I forgot about that! 😅 

Done. What about these duplicates? Probably generated because of multiple entry points.

https://github.com/google/webcrypto.dart/blob/b5c79268214ac1af2b1835dbc3a0584cdb436d79/lib/src/third_party/boringssl/generated_bindings.dart#L3789-L3811

I also filed https://github.com/dart-lang/ffigen/issues/176 because many structs reference some other struct that I'm not interested in.

**Comment by mannprerak2** [comment]
> Done. What about these duplicates? Probably generated because of multiple entry points.

Ah, that's a bug. Since we use `USR` to remove duplicates, we should mostly get this issue even with multiple entry points.

**Comment by mannprerak2** [comment]
> It generated them as Opaque.

I've filled an issue for this https://github.com/dart-lang/ffigen/issues/179. This happened due to forward declarations, which were in the `base.h` file -
```C
typedef struct cbb_st CBB;
typedef struct cbs_st CBS;
```
This goes away if the structs were excluded and hence only parsed when needed by any function.

---
Other notes: you should consider supplying `-Wno-nullability-completeness` in `compiler-opts` to remove null warnings from clang. I was also seeing `stdarg.h` not found on my system, If you were also seeing this you should resolve it soon or some missing types may randomly be assigned as `Int32` by libclang.

**Comment by dcharkes** [comment]
> -Wno-nullability-completeness

This has no effect for me with a newer Xcode (12.4).

> stdarg.h

That's because the path to Xcode on my machine is hardcoded in compiler opts. 🙈
