### ISSUE TITLE
Not working latest Xcode 16.0

### ISSUE THREAD

**Issue by faraz3796** [google/webcrypto.dart#150]
I just upgraded the iMac to MACOS sequoia. Now android is working fine but throwing issue on IOS build.

**Comment by faraz3796** [comment]
<img width="269" alt="Screenshot 2024-09-17 at 6 06 39 PM" src="https://github.com/user-attachments/assets/9c9b55ed-8f90-4b79-84d0-04b525ecc6d2">

**Comment by plusema86** [comment]
same here, @faraz3796 have you found a temporary solution?

**Comment by faraz3796** [comment]
> same here, @faraz3796 have you found a temporary solution?

Not yet

**Comment by punkaze** [comment]
same here

**Comment by CoreNion** [comment]
This issue is caused by the removed compiler option in xcode 16.
I've submitted a pull request (#154) with a fix, but if you're in a hurry, adding the following code to `[ios or macos]/Podfile` should fix the issue.

```ruby
post_install do |installer|
  ...
  installer.pods_project.targets.each do |target|
   ... 

   # Add these lines
    if target.name == 'webcrypto'
      target.source_build_phase.files.each do |file|
        if file.settings && file.settings['COMPILER_FLAGS']
          flags = file.settings['COMPILER_FLAGS'].split
          flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
          file.settings['COMPILER_FLAGS'] = flags.join(' ')
        end
      end
    end
  # End adding lines

  end
end
```
