### ISSUE TITLE
Very slow AES-CTR performance on Mac M1 (other arm64 too?  I will report back) 

### ISSUE THREAD

**Issue by cconstab** [google/webcrypto.dart#161]
I have been looking to replace/improve the AES-CTR streaming package that I am using at present (`encrypt`) which tops out at about 50mbps when using AOT.

 I got the webcrypto package working and see great improvements on Windows (up to 250mbps) but when testing on Mac M1 very poor results both in AOT and JIT..

When comparing with 
`package:better_cryptography/better_cryptography.dart' ---> Performs best in AOT/JIT
'package:encrypt/encrypt.dart'

JIT
```
String length: 5120 KB
-----------------------------------------------
Start software encrypt AESCTR
..........
1987 ms
201 mbps
software encrypt end
-----------------------------------------------
Start Better AES CTR
..........
2328 ms
180 mbps
Better end
Better faster by: -15%
-----------------------------------------------
Start BoringSSL AES CTR
..........
29881 ms
14 mbps
BoringSSL end
BoringSSL faster by: -93%
-----------------------------------------------
```

And AOT

```
String length: 5120 KB
-----------------------------------------------
Start software encrypt AESCTR
..........
6826 ms
59 mbps
software encrypt end
-----------------------------------------------
Start Better AES CTR
..........
2414 ms
174 mbps
Better end
Better faster by: 183%
-----------------------------------------------
Start BoringSSL AES CTR
..........
30730 ms
14 mbps
BoringSSL end
BoringSSL faster by: -78%
-----------------------------------------------
```

**Comment by cconstab** [comment]
For comparison same code running on Windows..

JIT
```
-----------------------------------------------
String length: 5120 KB
-----------------------------------------------
Start software AESCTR
..........
2672 ms
150 mbps
software end
-----------------------------------------------
Start Better AES CTR
..........
1411 ms
297 mbps
Better end
Better faster by: 89%
-----------------------------------------------
Start BoringSSL AES CTR
..........
1441 ms
291 mbps
BoringSSL end
BoringSSL faster by: 85%
----------------------------------------------- 
```

and AOT

```
-----------------------------------------------
String length: 5120 KB
-----------------------------------------------
Start software AESCTR
..........
8613 ms
46 mbps
software end
-----------------------------------------------
Start Better AES CTR
..........
1652 ms
254 mbps
Better end
Better faster by: 421%
-----------------------------------------------
Start BoringSSL AES CTR
..........
2429 ms
173 mbps
BoringSSL end
BoringSSL faster by: 255%
-----------------------------------------------
```

**Comment by cconstab** [comment]
So on Linux the same thing until noticed the .so was not being picked up.. Added LD_LIBRARY_PATH into the mix and my "DART" buin started acting correctly.
Note I am using Dart not Flutter so I end up with a clean CLI app.. Just remember to include the .so's in the PATH (doh!)..

Mac Flutter not building right now after Seq upgrade oh well :-)

**Comment by jonasfj** [comment]
On all platforms other than web this package shells out to BoringSSL.

If performance is slow, it might have to do with compiler options.
https://github.com/google/webcrypto.dart/blob/8ac145beef348a55f0e268f11101bc8f9a8e3fec/darwin/webcrypto.podspec#L29-L30

One could try to enable those options on Linux or Windows to see if you get similar performance degradation.

In which case it might be worth figuring out how to enable ASM on Mac/iOS. Or compile without `DDOPENSSL_SMALL` not targeting Android or iOS.

If you find an improvement PRs are appreciated.

**Comment by cconstab** [comment]
I closed while I work a little harder to solve and will raise PR once I have a solution rather than a problem :-)
