### ISSUE TITLE
Cleanup _withAllocation and _withAllocationAsync

### ISSUE THREAD

**Issue by dcharkes** [google/webcrypto.dart#19]
We should cleanup `_withAllocation` and `_withAllocationAsync` to use `_Scope`.

Possibly we can adopt the `Pool`-pattern from the samples everywhere.

```dart
  // In a pool multiple resources can be allocated, which will all be freed
  // at the end of the scope.
  using((Pool pool) {
    final p = pool<Int64>(2);
    final p2 = pool<Int64>(2);
    p[0] = 1;
    p[1] = 2;
    MemMove(p2.cast<Void>(), p.cast<Void>(), 2 * sizeOf<Int64>());
    Expect.equals(1, p2[0]);
    Expect.equals(2, p2[1]);
  });
```
https://github.com/dart-lang/sdk/blob/master/samples/ffi/resource_management/pool_sample.dart#L48-L58

 (Or even merge `Pool` to `package:ffi` and use it.)

**Comment by jonasfj** [comment]
Migrated everything to use `_Scope` which is very similar to `Arena`.
