### ISSUE TITLE
Possible to sign data with Sha1withRSA?

### ISSUE THREAD

**Issue by gabucito** [google/webcrypto.dart#3]
Hello, I was wondering if with this package one could sign data with the SHA1withRSA algorithm.

**Comment by jonasfj** [comment]
The term `SHA1withRSA` does not specify an signature scheme. There are multiple RSA schemes:
 * [RSASSA-PKCS1-v1_5](https://pub.dev/documentation/webcrypto/latest/webcrypto/RsassaPkcs1V15PrivateKey-class.html)
 * [RSA-PSS](https://pub.dev/documentation/webcrypto/latest/webcrypto/RsaPssPrivateKey-class.html)

Often RSA means `RSASSA-PKCS1-v1_5`, but you should look up documentation for the system your integrating with, or simply try to see which one works :)

The API documentation actually has an example of how to import a PEM encoded private key, and sign with `RSASSA-PKCS1-v1_5` and SHA-256:
https://pub.dev/documentation/webcrypto/latest/webcrypto/RsassaPkcs1V15PrivateKey/signBytes.html

You can just use [Hash.sha1](https://pub.dev/documentation/webcrypto/latest/webcrypto/Hash/sha1-constant.html) instead.

However, you should probably only use SHA-1 for integration with legacy systems.
