### ISSUE TITLE
Lacks support for pure-Dart use

### ISSUE THREAD

**Issue by serverwentdown** [google/webcrypto.dart#33]
It would be nice to split this package into two parts, one for pure-Dart use, and the other for use in Flutter.

Reference:
- https://github.com/jpnurmi/libserialport.dart
- https://github.com/jpnurmi/flutter_libserialport

**Comment by jonasfj** [comment]
I don't want to go down this route... I would rather find a mechanism for shipping a plugin package that works with both Dart and Flutter, so as to not fragment the ecosystem.

**Comment by jonasfj** [comment]
Filed https://github.com/google/webcrypto.dart/issues/192 which is where we'll track progress towards allowing this package to work without Flutter.
