### ISSUE TITLE
Possible to split into packages so that the non-flutter parts can be used in a non-flutter project?

### ISSUE THREAD

**Issue by matehat** [google/webcrypto.dart#43]
In one of our non-flutter project, we need to do encryption/decryption on the Web platform. I see that most of our needs are fulfilled by this library, but the library requires the Flutter SDK.

Would it be thinkable that this library be split in multiple packages (like [this one](https://github.com/simolus3/drift)), where specific implementations (in our case, the web one) can be depended on without dragging with it a dependency on Flutter?

**Comment by matehat** [comment]
I see that this issue [has already been raised](https://github.com/google/webcrypto.dart/issues/33). Sorry for the bother.

---

But I still want to point out that this is an unfortunate decision. Most of the ecosystem seem to solve that problem in that manner.

**Comment by jonasfj** [comment]
I agree this is a problem.

For this package I'm working on improving the interface / documentation / tests, etc. I know that there is work in progress for shipping Dart "plugins" too.

In the mean time, I'd suggest just vendoring with something like:
https://pub.dev/packages/vendor

Then you don't need to fork, and you can just copy the files you need and use it. It's an ugly hack, but solves your immediate issue.

**Comment by jonasfj** [comment]
Filed https://github.com/google/webcrypto.dart/issues/192 which is where we'll track progress towards allowing this package to work without Flutter.
