### ISSUE TITLE
Ques: How to generate public/private Key RSA-OAEP ?

### ISSUE THREAD

**Issue by 2002Bishwajeet** [google/webcrypto.dart#46]
I was looking through your package and didn't find any similar documentation or something on generating public/private RSA-OAEP key.  

I did find [this ](https://github.com/google/webcrypto.dart/blob/master/lib/src/webcrypto/webcrypto.rsaoaep.dart#L96) but I am not sure if that's what I am looking for??

**Comment by jonasfj** [comment]
You're probably looking for:
https://pub.dev/documentation/webcrypto/latest/webcrypto/RsaOaepPrivateKey/generateKey.html

That'll generate a KeyPair.
