### ISSUE TITLE
Dart (server) apps support

### ISSUE THREAD

**Issue by lesnitsky** [google/webcrypto.dart#69]
Given that this package uses ffi and BoringSSL, what is blocking from decoupling this package from Flutter and provide it for pure dart applications?

**Comment by jonasfj** [comment]
Not really anything, we do not have a mechanism for expressing optional dependency on Flutter :/

But ongoing work for native plugins for Dart is progressing.

Honestly, you might be able to use it from a Dart SDK with a `dependency_override`, I haven't tested it.

**Comment by jonasfj** [comment]
Filed https://github.com/google/webcrypto.dart/issues/192 which is where we'll track progress towards this goal.
